[package]
name = "easycon-runtime"
description = "Operations, cancellation, events, and lifecycle for EasyCon SDK"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
runtime-model = []

[dependencies]
easycon-model = { path = "../easycon-model" }

[dev-dependencies]
loom = "0.7.2"

[lints]
workspace = true
