#!/usr/bin/env python3
"""Generate or verify synthetic Phase 3 matching, edge, and HSV fixtures."""

import argparse
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = ROOT / "spec" / "fixtures" / "vision" / "operations"

TEMPLATE_SEARCH = bytes(
    [
        10, 30, 80, 20, 90, 40,
        60, 15, 110, 55, 5, 200,
        70, 90, 40, 150, 25, 35,
        20, 130, 75, 65, 180, 45,
        200, 10, 95, 120, 30, 160,
    ]
)
TEMPLATE_TARGET = bytes([110, 55, 5, 40, 130, 25, 75, 65, 180])

EDGE_TARGET_WIDTH = 11
EDGE_TARGET_HEIGHT = 11
EDGE_SEARCH_WIDTH = 18
EDGE_SEARCH_HEIGHT = 17
EDGE_X = 4
EDGE_Y = 3


def make_edge_target():
    pixels = bytearray([10] * (EDGE_TARGET_WIDTH * EDGE_TARGET_HEIGHT))
    feature = ((30, 200, 60), (150, 40, 220), (80, 180, 120))
    for row, values in enumerate(feature, start=4):
        start = row * EDGE_TARGET_WIDTH + 4
        pixels[start:start + 3] = bytes(values)
    return bytes(pixels)


def embed(source, source_width, target_width, target_height, x, y, fill):
    output = bytearray([fill] * (target_width * target_height))
    source_height = len(source) // source_width
    for row in range(source_height):
        source_start = row * source_width
        target_start = (y + row) * target_width + x
        output[target_start:target_start + source_width] = source[
            source_start:source_start + source_width
        ]
    return bytes(output)


EDGE_TARGET = make_edge_target()
EDGE_SEARCH = embed(
    EDGE_TARGET,
    EDGE_TARGET_WIDTH,
    EDGE_SEARCH_WIDTH,
    EDGE_SEARCH_HEIGHT,
    EDGE_X,
    EDGE_Y,
    10,
)

# Independently captured OpenCV 4.x outputs for the frozen EasyCon algorithms.
# These are data, not recomputed through the bridge under test.
EDGE_XY_TARGET = bytes(
    [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 60, 255, 255, 250, 0, 0, 0, 0,
        0, 0, 0, 255, 255, 255, 100, 0, 0, 0, 0,
        0, 0, 0, 255, 255, 255, 0, 0, 0, 0, 0,
        0, 0, 0, 255, 150, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ]
)
EDGE_LAPLACIAN_TARGET = bytes.fromhex(
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000ff000000000000ffffff0000ff000000ff00ffffffff00ff0000000000ffffff0000ff00000000000000000000000000000000000000000000000000000000ffff000000000000000000000000000000"
)
EDGE_XY_SEARCH = embed(
    EDGE_XY_TARGET,
    EDGE_TARGET_WIDTH,
    EDGE_SEARCH_WIDTH,
    EDGE_SEARCH_HEIGHT,
    EDGE_X,
    EDGE_Y,
    0,
)
EDGE_LAPLACIAN_SEARCH = embed(
    EDGE_LAPLACIAN_TARGET,
    EDGE_TARGET_WIDTH,
    EDGE_SEARCH_WIDTH,
    EDGE_SEARCH_HEIGHT,
    EDGE_X,
    EDGE_Y,
    0,
)

HSV_BGR = bytes(
    [
        0, 0, 255, 0, 128, 255, 0, 255, 255, 0, 255, 0, 255, 255, 0,
        255, 0, 0, 255, 0, 255, 42, 0, 255, 0, 43, 255, 255, 255, 255,
        0, 0, 0, 128, 128, 128, 48, 43, 200, 43, 0, 128, 0, 0, 255,
    ]
)


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def generated_files():
    if len(EDGE_XY_TARGET) != EDGE_TARGET_WIDTH * EDGE_TARGET_HEIGHT:
        raise ValueError("XY reference fixture dimensions differ")
    if len(EDGE_LAPLACIAN_TARGET) != EDGE_TARGET_WIDTH * EDGE_TARGET_HEIGHT:
        raise ValueError("Laplacian reference fixture dimensions differ")
    payloads = {
        "template-search-gray.hex": TEMPLATE_SEARCH,
        "template-target-gray.hex": TEMPLATE_TARGET,
        "edge-search-gray.hex": EDGE_SEARCH,
        "edge-target-gray.hex": EDGE_TARGET,
        "edge-search-xy-gray.hex": EDGE_XY_SEARCH,
        "edge-target-xy-gray.hex": EDGE_XY_TARGET,
        "edge-search-laplacian-gray.hex": EDGE_LAPLACIAN_SEARCH,
        "edge-target-laplacian-gray.hex": EDGE_LAPLACIAN_TARGET,
        "hsv-bgr-5x3.hex": HSV_BGR,
    }
    files = {
        name: data.hex().encode("ascii") + b"\n" for name, data in payloads.items()
    }
    manifest = {
        "version": 1,
        "license": "GPL-3.0-only",
        "generator": "tools/generate_vision_operation_fixtures.py",
        "reference_opencv": "4.12.0",
        "provenance": (
            "Synthetic pixels authored for EasyCon SDK Phase 3. Expected edge "
            "pixels and normalized extrema were independently captured from the "
            "frozen OpenCV algorithms and are never generated by the bridge under test."
        ),
        "template": {
            "search": {"width": 6, "height": 5, "format": "Gray8"},
            "target": {"width": 3, "height": 3, "format": "Gray8"},
            "expected": {
                "x": 2,
                "y": 1,
                "raw_tolerance": 0.00001,
                "score_tolerance": 0.00001,
                "SqDiffNormed": {
                    "raw": 0.005045493599027395,
                    "score": 0.9949545064009726,
                },
                "CCorrNormed": {
                    "raw": 0.9981008172035217,
                    "score": 0.9981008172035217,
                },
                "CCoeffNormed": {
                    "raw": 0.9942602515220642,
                    "score": 0.9971301257610321,
                },
            },
        },
        "edge": {
            "search": {
                "width": EDGE_SEARCH_WIDTH,
                "height": EDGE_SEARCH_HEIGHT,
                "format": "Bgr8 replicated from fixture Gray8",
            },
            "target": {
                "width": EDGE_TARGET_WIDTH,
                "height": EDGE_TARGET_HEIGHT,
                "format": "Bgr8 replicated from fixture Gray8",
            },
            "expected": {
                "x": EDGE_X,
                "y": EDGE_Y,
                "raw": 1.0,
                "score": 1.0,
                "raw_tolerance": 0.00001,
                "score_tolerance": 0.00001,
            },
            "xy": (
                "BGR2GRAY; Scharr via Sobel CV_16S ksize=-1 in X and Y; "
                "addWeighted(0.5,0.5); saturating Gray8 conversion"
            ),
            "laplacian": (
                "BGR2GRAY; Gaussian 5x5 sigma=1.5; Laplacian CV_16S ksize=3; "
                "convertScaleAbs; binary threshold 30/255"
            ),
        },
        "hsv": {
            "image": {"width": 5, "height": 3, "format": "Bgr8"},
            "roi": {"x": 1, "y": 0, "width": 4, "height": 3},
            "cases": {
                "normal": {
                    "range": [20, 100, 200, 255, 200, 255],
                    "count": 3,
                    "ratio": 0.25,
                    "bbox": [2, 0, 3, 1],
                },
                "hue_wrap": {
                    "range": [170, 10, 100, 255, 100, 255],
                    "count": 5,
                    "ratio": 0.4166666666666667,
                    "bbox": [2, 1, 3, 2],
                },
                "full": {
                    "range": [0, 179, 0, 255, 0, 255],
                    "count": 12,
                    "ratio": 1.0,
                    "bbox": [1, 0, 4, 3],
                },
                "none": {
                    "range": [101, 110, 200, 255, 200, 255],
                    "count": 0,
                    "ratio": 0.0,
                    "bbox": None,
                },
            },
        },
        "files": [
            {
                "path": name,
                "decoded_bytes": len(data),
                "decoded_sha256": sha256(data),
            }
            for name, data in payloads.items()
        ],
    }
    files["manifest.json"] = (
        json.dumps(manifest, indent=2, ensure_ascii=True) + "\n"
    ).encode("utf-8")
    return files


def check(files):
    expected_names = set(files)
    actual_names = {path.name for path in FIXTURE_DIR.iterdir() if path.is_file()}
    failures = []
    if actual_names != expected_names:
        failures.append(
            "fixture file set differs: missing={}, extra={}".format(
                sorted(expected_names - actual_names),
                sorted(actual_names - expected_names),
            )
        )
    for name, expected in files.items():
        path = FIXTURE_DIR / name
        try:
            actual = path.read_bytes()
        except OSError as error:
            failures.append("{}: {}".format(path, error))
            continue
        if actual != expected:
            failures.append("{} is not reproducible from the tracked generator".format(path))
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    print("validated 9 generated vision operation fixtures and their manifest")
    return 0


def write(files):
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (FIXTURE_DIR / name).write_bytes(data)
    print("generated 9 vision operation fixtures and their manifest")
    return 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify tracked fixture bytes instead of replacing them",
    )
    arguments = parser.parse_args()
    files = generated_files()
    return check(files) if arguments.check else write(files)


if __name__ == "__main__":
    sys.exit(main())
